In [1]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])
res = a + b
print (res)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [3]:
matrix1 = [
    [1,2,3],
    [4,5,6]
]
a = len(matrix1)
print(a)
b = range(a)
print (b)

2
range(0, 2)


In [4]:
matrix1 = [
    [1,2,3],
    [4,5,6]
]
matrix2 = [
    [1,2,3],
    [4,5,6]
]
result = [
    [0,0,0],
    [0,0,0]
]

for i in range(len(matrix1)):
    for j in range(len(matrix2)):

        result[i][j] = matrix1[i][j] + matrix2[i][j]

print ('Matrix 1:')
for row in matrix1:
    print (row)

print ('\nMatrix 2:')
for row in matrix2:
    print (row)

print ('\n Sum of matrix 1 and matrix 2:')
for row in result:
    print (row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]

Matrix 2:
[1, 2, 3]
[4, 5, 6]

 Sum of matrix 1 and matrix 2:
[2, 4, 0]
[8, 10, 0]
